# Generated by Django 5.2 on 2025-04-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='available',
        ),
        migrations.AddField(
            model_name='menu',
            name='cuisine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Menu', to='my_app.cuisine'),
        ),
    ]
