# Generated by Django 5.2 on 2025-04-18 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_cuisine_remove_menu_available_menu_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cuisine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='my_app.cuisine'),
        ),
    ]
