# Generated by Django 5.2 on 2025-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_logger_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AlterField(
            model_name='logger',
            name='time_log',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
