# Generated by Django 5.2 on 2025-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_delete_shift_alter_logger_time_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
