# Generated by Django 5.2 on 2025-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='count',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
