# Generated by Django 5.2 on 2025-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_reservation_count_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('description', models.TextField(default=None)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='count',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
