# Generated by Django 5.2 on 2025-04-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_services_remove_menu_cuisine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservation',
        ),
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
